foundweekends/giter8

- README.markdown
I always wanted what these tests were, until I stumpled upon the blog post which explains it.
> Provide link to testing sbt plugins

- plugin/src/sbt-test/giter8/simple/src/main/g8/default.properties
fix #177
ref https://github.com/softprops/ls/issues/76
> avoid ls, because ls.implicit.ly returns status 500

- plugin/src/main/scala/giterate-plugin.scala
This should resolve issue #150
> Resolve dynamic default properties

- app/src/main/scala/apply.scala
- project/build.scala
This PR allows to specify ssh password of your certificates, as the password.
I think it corrects #163 
Should you need to PR to master?
> SSH Passphrase prompt

- build.sbt
- library/src/test/scala/FormatSpecification.scala
- project/Dependencies.scala
It seemed like the topic of testing came up in #154, so I added a simple property-based testing as a starter.
/review @xuwei-k
> Implement simple property-based testing for G8 formatting

- app/src/main/scala/apply.scala
- src/main/conscript/g8/launchconfig
It would be cool to support `ssh://` git projects too.
> support git URLs that start with ssh://

- app/src/main/scala/giter8.scala
> n8han to foundweekends

- app/src/main/scala/giter8.scala
- build.sbt
- library/src/main/scala/JgitHelper.scala
- library/src/main/scala/g8.scala
- notes/0.7.0.markdown
- project/Dependencies.scala
This PR is implemented on top of #202
`--version` is called by conscript the first time it's installed.
Fixes #188
> Adds --version

- docs/03/b.md
- docs/04/00.md
http://www.foundweekends.org/giter8/scaffolding.html
> fix missing double quotes

- docs/03/b.md
- docs/ja/03/b.md
https://github.com/foundweekends/giter8/commit/198ed47c659a15e46c5fb6495c547c60f3582e38#diff-fdc3abdfd754eeb24090dbd90aeec2ceR66
> fix plugin name in docs

- build.sbt
- project/Dependencies.scala
Fixes #211
Now slf4j will found an implementation
Edit: Sorry for reference 218 issue
> Added logback dependency

- build.sbt
- project/Dependencies.scala
I'm not sure why g8 depends on jline.
https://github.com/foundweekends/giter8/commit/1e5b60d6b5dac2b5b1950
> remove jline

- .travis.yml
https://github.com/sbt/sbt-ghpages/commit/cbedd8edb8
> set SBT_GHPAGES_COMMIT_MESSAGE

- build.sbt
- library/src/main/scala/g8.scala
- library/src/test/scala/FormatSpecification.scala
> Snake format changes hyphen to underscore

- app/src/main/scala/giter8.scala
- library/src/main/scala/giter8/JgitHelper.scala
- library/src/test/scala/giter8/JgitHelperTest.scala
Very basic directory config param handling for rendering from git repo with g8 sub-directory templates
Basic implementation since the project in my Intellij is full or errors. Using 2.10.5 scala. It just not compiles properly. Any idea? 
I used console sbt but to verify. It can be more sophisticated and it can have more tests as well..
> Implement a naive directory config attribute handling #268

- library/src/main/scala/maven.scala
reopening #155 
I have added possiblity to configure maven repository for fetching latest version. You need to configure $G8_HOME/mvnrepo file like this:
```
$ cat ~/.g8/mvnrepo 
http://nexus:8081/nexus/
```
> configuration for maven repo in G8_HOME/mvnrepo file

- project/Dependencies.scala
Reverts foundweekends/giter8#281
https://github.com/scala/scala/pull/5821
> Revert "Scala 2.11.9"

- library/src/test/scala/giter8/VersionNumberOrderingTest.scala
The existing tests only covered sorting by major version, which
left gaps should the sorting fail on minor or patch versions. Added
more properties to ensure the sorting of VersionNumber is correctly
tested through the major, minor and patch variations.
> add properties around corner cases for VersionNumber sorting

- library/src/main/scala/g8.scala
> Restore force override functionality

- app/src/main/scala/giter8.scala
> fport: Add an optional baseDirectory parameter to run()

- library/src/main/scala/giter8/Ls.scala
- library/src/main/scala/maven.scala
> ls() workaround

- library/src/main/scala/giter8/GitRepository.scala
> Default to HTTPS for accessing GitHub

- .scalafmt.conf
- .travis.yml
- app/src/main/scala/giter8.scala
- library/src/main/scala/g8.scala
- library/src/main/scala/giter8/MavenHelper.scala
- library/src/main/scala/giter8/VersionNumber.scala
- library/src/main/scala/giter8/package.scala
- library/src/main/scala/maven.scala
- library/src/test/scala/giter8/MavenTest.scala
- library/src/test/scala/giter8/VersionNumberOrderingTest.scala
- plugin/src/main/scala/Giter8Plugin.scala
- project/Dependencies.scala
- project/Publish.scala
- project/TravisSitePlugin.scala
- project/plugins.sbt
- update scalafmt 0.6.8
- set "docstrings = JavaDoc"
> execute scalafmtTest in travis-ci

- docs/03/00.md
- library/src/main/scala/g8.scala
- library/src/main/scala/giter8/AugmentedString.scala
- library/src/main/scala/giter8/Truthy.scala
- library/src/test/scala/giter8/IntegrationTest.scala
- library/src/test/scala/giter8/IntegrationTestHelpers.scala
Adds `truthy` property to all fields so they can be used in conditionals while retaining their original string values.
> Support for conditionals #157

- docs/03/00.md
> Fix a typo.

- library/src/main/scala/g8.scala
- library/src/test/scala/FormatSpecification.scala
- library/src/test/scala/giter8/IntegrationTest.scala
- library/src/test/scala/giter8/VerbatimTest.scala
Also, check if a file should be copied verbatim relatively from the template root.
Fixes #339
> Use gitignore format for verbatim arguments

- docs/03/00.md
This is to close issue [345](https://github.com/foundweekends/giter8/issues/345) and add an example for others that are looking to do this.
> #345 Add example for conditional files.

- library/src/main/scala/g8.scala
https://github.com/scala/scala/blob/5661290bfda0a08a60fb8df3ac60baafb55c0306/src/library/scala/collection/IterableOnce.scala#L465
> use foldLeft instead of /:

- plugin/src/main/scala/Giter8Plugin.scala
> Copy scaffolds in g8 and g8Test

- build.sbt
- plugin/src/sbt-test/giter8/simple/build.sbt
- plugin/src/sbt-test/giter8/without-name/build.sbt
https://github.com/scala/scala/blob/v2.12.6/src/library/scala/sys/process/package.scala#L204-L210
> avoid scala.sys.process.javaVmArguments

- project/Dependencies.scala
This is  a resend of https://github.com/foundweekends/giter8/pull/353
> Bump to JGit 4.9.0.201710071750-r

- library/src/main/scala/maven.scala
This is a resend of https://github.com/foundweekends/giter8/pull/379
> fix default g8 home resolution #155

- app/src/main/scala/giter8.scala
> Add help for -o/--out

- build.sbt
- plugin/src/main/scala-sbt-0.13/sbt/sbtgiter8/SBTCompat.scala
- plugin/src/main/scala-sbt-1.0/sbt/sbtgiter8/SBTCompat.scala
- plugin/src/main/scala/Giter8Plugin.scala
- project/Dependencies.scala
- project/build.properties
Fixes #406
This is a minimized version of #412. 
Co-authored-by: eugene yokota <eed3si9n@gmail.com>
> Use sbt 1.2.8

- library/src/main/scala/giter8/MavenHelper.scala
Fixes https://github.com/foundweekends/giter8/issues/440
Apparently Apache HTTP client's DefaultHttpClient is having issue behind the firewall. This attempts to fix it by switching to URL#openConnection.
> switch to using URL#openConnection

- library/src/main/scala/g8.scala
This is a workaround for https://github.com/antlr/stringtemplate4/issues/253.
It is a partial fix for https://github.com/foundweekends/giter8/issues/460 but the ultimate fix will be to update ST4 once there is a new release with the bug fix.
> Add workaround for NPE

- .travis.yml
- build.sbt
- cli-git/src/main/scala/ConsoleCredentialsProvider.scala
- cli-git/src/main/scala/GitInteractor.scala
- launcher/src/main/scala/LauncherMain.scala
- launcher/src/test/scala/LauncherTest.scala
- project/Dependencies.scala
- project/build.properties
Fixes https://github.com/foundweekends/giter8/issues/469
Ref https://github.com/foundweekends/giter8/pull/459
> Fix SshAgentSessionFactory

- build.sbt
- project/Publish.scala
- project/plugins.sbt
fix https://github.com/foundweekends/giter8/issues/513
> use sonatype instead of bintray
